### ISSUE TITLE
Variable for site tagline in a slot?

### ISSUE THREAD

**Issue by iainhallam** [ComboStrap/website#3]
I've used the `$lead` variable to include the DokuWiki configuration for tagline in the text of my home page, and it works fine, but then I used it in a footer slot, and it's empty while showing the home page. Going to another page on the site, of course it takes the lead from that page. Is there a variable that will give me the site's tagline in the footer slot from any page in the site?

**Comment by iainhallam** [comment]
I've just realised that because I opened this issue from the web site, it's put it in the site repo.

**Comment by gerardnico** [comment]
I didn't see it ;) at your service
